# Build Container
FROM docker.io/golang:alpine AS builder
RUN apk update && \ 
apk add git && \
CGO_ENABLED=0 go install -a -ldflags '-s' \
github.com/spkane/scratch-helloworld@latest

# Prod container, the "scratch" is a special image name telling Docker to start from an empty image

FROM scratch
COPY --from=builder  /go/bin/scratch-helloworld /helloworld
EXPOSE 8080
CMD [ "/helloworld" ]